### ISSUE TITLE
How long have you been learning Main training?

### ISSUE THREAD

**Issue by junsang7777** [dvlab-research/VFIformer#5]
Hello. Thank you for sharing the code of a good paper.

How long have you been learning Main training?
What did the GPU use when training, and how long does it take to learn all the 300 epochs written on the code?

**Comment by SkyeLu** [comment]
Hi, we train the model on 8 GeForce RTX 3090 for about 4 days.

**Comment by junsang7777** [comment]
Thank you for your quick reply.
