### ISSUE TITLE
Issue when i want to train

### ISSUE THREAD

**Issue by hnsnsjkf** [dvlab-research/VFIformer#6]
![image](https://user-images.githubusercontent.com/30283492/196232024-a5ef373b-87f2-44c6-8caf-f052de468865.png)
the size of my image is 864*96，but i meet this isue when i running the code

**Comment by hnsnsjkf** [comment]
can you tell me that param should i change when the crop_size is changed?

**Comment by SkyeLu** [comment]
Hi, under the current setting (window_size=8), both the length and width of input images must be multiples of 64. It is impossible to train the model on images whose width is only 96 with window_size=8. You may try out a smaller window_size, e.g., 4 or 2.

**Comment by hnsnsjkf** [comment]
it works,thank you

**Comment by hnsnsjkf** [comment]
Well, i got another question: the memory of the CUDA is continuesly rising when i was trainning, is it right?

**Comment by hnsnsjkf** [comment]
我看论文，作者好像是中国人，我直接用中文啦哈哈哈哈哈，我想问一下我跑模型，随着训练时间的增加，显卡的内存持续增加（从5G一直涨到爆显存）是什么情况呀
